main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('create/', views.create, name='create'),
    path('register<int:index/', views.register, name='register')
    

]

storynyappw/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.
class CreateModel (models.Model):
	event 		= models.CharField(max_length=50)

	def __str__(self):
		return "{}".format(self.event)

class RegisterModel(models.Model):
	kegiatan = models.ForeignKey(CreateModel, on_delete = models.CASCADE)
	register = models.CharField(max_length=50)

	def __str__(self):
		return "{}".format(self.register)

main/forms.py
from django import forms
from .models import CreateModel, RegisterModel

class NamaKegiatan(forms.ModelForm):
	class Meta:
		model = CreateModel
		fields = [
		'event'
		]

		labels = {
			'event' : 'Nama Kegiatan',
		}

		widgets = {
			'event' : forms.TextInput(
				attrs = {
					'class' : 'form-control',
					'placeholder' : 'Masukkan nama event',}
				)
		}

class DaftarKegiatan(forms.ModelForm):
	class Meta:
		model = RegisterModel
		fields = [
		'register'
		]

		labels = {
			'register' : 'Nama Lengkap',
		}

		widgets = {
			'register' : forms.TextInput(
				attrs = {
					'class' : 'form-control',
					'placeholder' : 'Masukkan nama Anda',}
				)
		}


 

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import NamaKegiatan, DaftarKegiatan
from .models import CreateModel, RegisterModel


def home(request):
	posts 	= CreateModel.objects.all()
	post 	= RegisterModel.objects.all()

	context ={
		'page_title': 'Daftar Kegiatan',
		'posts_form' : posts,
		'post_form' : post,
	}
	return render(request, 'main/home.html', context)

def create(request):
	posts_form = NamaKegiatan(request.POST or None)
	if request.method == "POST":
		if posts_form.is_valid():
			posts_form.save()
			
			return redirect ("main:home")
	
	context = {
		'page_title': 'Event',
		'posts_form' : posts_form,
	}
	return render (request, 'main/create.html', context)

def register(request):
	post_form = DaftarKegiatan(request.POST or None)
	if request.method == "POST":
		if post_form.is_valid():
			people = post_form.save(commit=False)
			people.kegiatan_id = CreateModel.objects.get(id=index).id
			people.save()

			return redirect("main:home")
		
	context = {
		'page_title': 'Register',
		'post_form' : post_form,
	}
	return render (request, 'main/register.html', context)

main/templates/main/create.html
{% extends "base.html" %} 
{% load static %}

{% block meta %}
	{{page_title}}
{% endblock meta %}

{% block content %}
	<h1 class = "text-center" style="margin-top: 100px"> {{page_title}} </h1>

	<form method= "POST">
		{% csrf_token %}
		<div class = "container">
			<div class="form-group container" style="margin-top: 10px">
				{{posts_form.event.label}}
				{{posts_form.event}}

			<button class="btn btn-primary" type="Submit" style="margin-top: 10px">Create Event</button>
			</div>
		</div>
	</form>
{% endblock content %}

main/templates/main/home.html
{% extends "base.html" %} 
{% load static %}

{% block meta %}
    {{page_title}}
{% endblock meta %}

{% block content %}
<body style = "background-color:#F3AD78"> 
    <!--Isi Website-->
    <div id="home">
        <div class="container">
            <div class="row">
                <div class="col-md">
                    <div class="judul" style="margin-top: 100px">
                        <h1 class="text-center" style="color: black;">{{page_title}}</h1>
                    </div>
                </div>
            </div>    
        </div>
        <div class="container">
            <div class="row">
                 <div class="col-md">
                    <a href = "{% url 'main:create'%}" class="btn btn-primary" type="Submit" style = "width: 150px">Create Event</a>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                {% for x in posts_form %}
                    <div class="col-md-4">
                       <div class="card" style="width: 18rem; margin-top: 10px">
                            <div class="card-body">
                                <h5 class="card-title text-center">{{x.event}}</h5>
                                {% for y in post_form %}
                                    {% if y.kegiatan_id == x.id %}
                                        <p class="card-text">{{y.register}}</p>
                                    {% endif %}
                                {% endfor %}
                                <a href = "{% url 'main:register' %}" class="btn btn-primary" type="Submit">Register</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}   
            </div> 
        </div>
    </div>
</body>
{% endblock content %}

main/templates/main/register.html
{% extends "base.html" %} 
{% load static %}

{% block meta %}
	{{page_title}}
{% endblock meta %}

{% block content %}
	<h1 class = "text-center" style = "margin-top: 100px"> {{page_title}} </h1>

	<form method= "POST">
		{% csrf_token %}
		<div class = "container">
			<div class="form-group container" style="margin-top: 10px">
				{{post_form.register.label}}
				{{post_form.register}}

			<button class="btn btn-primary" type="Submit" style="margin-top: 10px">Register Now!</button>
			</div>
		</div>
	</form>
{% endblock content %}

templates/base.html
'{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  	<meta charset="UTF-8">
  	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  	<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" media="all"?>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"crossorigin="anonymous">
  {% block meta %}
  <title>Lilis Safitri</title>
  {% endblock meta %}
</head>

<body>
	<nav class="navbar fixed-top navbar-expand-lg navbar-light scrolling-navbar" style="background-color:#F3AD78">
    <div class="container">
        <a class="navbar-brand nav-link" href="{% url 'main:home' %}">Lilis Safitri</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link active" href="{% url 'main:home' %}">Home<span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link active" href="{% url 'main:create' %}">Create</a>
            <a class="nav-item nav-link active" href="{% url 'main:register' %}">Register</a>
            <a class="nav-item nav-link active" href="{% url 'admin:index' %}">Admin</a>
          </div>
        </div>
    </div>
  </nav>


  {% block content %}
  {% endblock content %}
  <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/script.js' %}"></script>
</body>
</html>